#!/usr/bin/perl

use strict;
use warnings;

use Data::GUID;
use Carp;
use Path::Abstract;
use Document::Stembolt;
use DateTime;
use Document::Cabinet;

sub abort(@) {
    print join "", @_, "\n" if @_;
    exit -1;
}

my $cabinet = Document::Cabinet->new;
my $root = $cabinet->var_cabinet_dir;

sub article {

    return unless @_;

    my $folder;
    if (($folder = $_[0]) =~ s/^\.//) {
        shift @_;
    }
    else {
        $folder = "Unfiled";
    }
    $folder = $root->subdir($folder);

    return unless @_;

    my $title = join " ", @_;

    my $uuid = lc Data::GUID->new->as_string;
    my $name = $title;
    $name =~ s/[^A-Za-z0-9]/-/g;
    $name =~ s/-+/-/g;
    my $file = join '-', $name, $uuid;
    my $path = $folder->subdir($file);

    return {
        folder => $folder,
        path => $path,
        file => $file,
        title => $title,
        uuid => $uuid,
        name => $name,
    };
}

sub folder_title {

    return unless @_;

    my $folder;
    if (($folder = $_[0]) =~ s/^\.//) {
        shift @_;
    }
    else {
        $folder = "Unfiled";
    }
#    $folder = $root->subdir($folder);

    return unless @_;

    my $title = join " ", @_;

    return ($folder, $title);
}

sub list {
    my $search = shift;
    for my $post ($search->search(undef, { order_by => ['cdtime'] })) {
        print join " ", $post->uuid, $post->title;
        print "\n";
    }
}

local $_ = $0;
if (m/\barticle-new$/) {
    my ($folder, $title) = folder_title @ARGV or abort "Wasn't given an article to edit";
    $cabinet->new_post($folder, $title);
}
elsif (m/\barticle-edit$/) {
    my $key = shift @ARGV or goto article_LIST;

    my ($post, $search, $count, $many);
    $count = ($search = $cabinet->model->search(post => { title => $key }))->count;

    if ($count == 1) {
        ($post) = $search->slice(0, 0);
    }
    elsif ($count > 1) {
        $many = $search;
    }
    else {
        $count = ($search = $cabinet->model->search(post => { uuid => { -like => "$key%" } }))->count;
        if ($count == 1) {
            ($post) = $search->slice(0, 0);
        }
        elsif ($count > 1) {
            $many = $search;
        }
        else {
            abort "Didn't find any matches";
        }
    }

    if ($many) {
        print "Which did you want?\n";
        list $many;
    }
    else {
        $cabinet->edit_post($post);
    }


    
#    my $article = article @ARGV or abort "Wasn't given an article to edit";
#    my $document = Document::Stembolt->new(file => $article->{path}->file);
#    unless (-e $document->file) {
#        $document->header->{title} = $article->{title};
#        $document->header->{uuid} = $article->{uuid};
#        $document->header->{cdtime} = DateTime->now->set_time_zone('UTC')->strftime("%F %T %z");
#    }
#    $document->edit;
}
elsif (m/\barticle-list$/) {
article_LIST:
    list scalar $cabinet->model->search(post => {});
}
elsif (m/\barticle-retitle$/) {
}
else {
    abort "Don't know what you want me to do";
}

